name: 1 - hello - world

on: workflow_dispatch

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print hello
              run: echo "Hello World"
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hi again
              run: echo "Hi AGAIN"
            - name: An step for Pass
              run: exit 0
            - name: Print GoodBye
              run: echo "Goodbye"
